version: '3.8'
services:
    app:
        build:
            context: .
        command: gunicorn django_movie.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_data:/vol/static
        ports:
            - "8000:8000"
        restart: always
        env_file:
            - ./.env.prod
        depends_on:
            - app-db
    app-db:
        image: postgres:14
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data:rw
        env_file:
            - ./.env.prod
    proxy:
        build: ./proxy
        volumes:
            - static_data:./.django_movie/static
            - media_data:./.django_movie/media
        restart: always
        ports:
            - "8000:80"
        depends_on:
            - app
    redis:
        image: redis:latest
        hostname: redis
        ports:
            - "0.0.0.0:6379:6379"
        env_file:
            - ./dev.prod
    celeryworker:
        depends_on:
            - redis
            - app-db
        command: "celery -A django_movie worker -l info"
    celery-beat:
        depends_on:
            - redis
            - app-db
        command: "celery -A django_movie beat -l info"
    celery-flower:
        depends_on:
            - redis
        command: "celery -A django_movie flower --basic_auth=test_user:password_user"
volumes:
    static_data:
    postgres_data: